# Generated by Django 4.0.5 on 2022-07-02 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('author', models.JSONField()),
                ('year', models.DateField()),
                ('journal', models.CharField(max_length=250)),
                ('volume', models.IntegerField()),
                ('number', models.IntegerField()),
                ('publisher', models.JSONField()),
                ('pages', models.CharField(max_length=100)),
                ('abstract', models.TextField()),
                ('langid', models.CharField(blank=True, max_length=100)),
                ('annotations', models.JSONField()),
                ('issn', models.JSONField()),
                ('doi', models.JSONField()),
                ('keywords', models.JSONField()),
                ('file', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(auto_created=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='normalNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(auto_created=True)),
                ('name', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=200)),
                ('main_content', models.TextField()),
                ('folder_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.type')),
                ('parent_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.folder')),
                ('tags', models.ManyToManyField(to='notes.tags')),
            ],
        ),
        migrations.AddField(
            model_name='folder',
            name='folder_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.type'),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ManyToManyField(to='notes.folder'),
        ),
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='papers', serialize=False, to='notes.normalnotes')),
                ('year', models.DateField()),
                ('link', models.URLField()),
                ('bibtex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.citations')),
            ],
        ),
    ]
