# Generated by Django 4.0.5 on 2022-07-03 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_remove_folder_parent_folder_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='folder_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.type'),
        ),
    ]
