# Generated by Django 4.0.5 on 2022-07-03 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_folder_folder_type_alter_folder_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normalnotes',
            old_name='folder_type',
            new_name='note_type',
        ),
    ]
