# Generated by Django 4.0.5 on 2022-07-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_rename_folder_type_normalnotes_note_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalnotes',
            name='tags',
            field=models.ManyToManyField(related_query_name='notes', to='notes.tags'),
        ),
    ]
