# Generated by Django 4.0.5 on 2022-07-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_alter_normalnotes_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalnotes',
            name='tags',
            field=models.ManyToManyField(related_name='note', related_query_name='notes', to='notes.tags'),
        ),
    ]
