# Generated by Django 4.0.5 on 2022-07-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_alter_normalnotes_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='citations',
            name='shorttitle',
            field=models.CharField(default='', max_length=350),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citations',
            name='title',
            field=models.CharField(max_length=700),
        ),
    ]
