# Generated by Django 4.0.5 on 2022-07-05 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_citations_shorttitle_alter_citations_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='citations',
            name='month',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
