# Generated by Django 4.0.5 on 2022-07-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_alter_citations_month_alter_citations_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='citations',
            name='name',
            field=models.CharField(default='BibText Test', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='papers',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
