# Generated by Django 4.0.5 on 2022-07-07 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_citations_name_alter_papers_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalnotes',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='normalnotes',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
