# Generated by Django 4.0.5 on 2022-07-07 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_folder_folder_as_dict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='folder_dict',
        ),
    ]
