# Generated by Django 4.0.5 on 2022-07-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0017_folder_folder_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='slug',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
