# Generated by Django 4.0.5 on 2022-07-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0019_alter_folder_folder_dict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True),
        ),
    ]
