# Generated by Django 4.0.5 on 2022-07-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0020_alter_folder_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='folder_dict',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
