# Generated by Django 4.0.5 on 2022-07-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0022_remove_normalnotes_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='breadcrumb_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='folder_tree_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='normalnotes',
            name='breadcrumb_html',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='subfiles',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='subfolders',
            field=models.JSONField(blank=True),
        ),
    ]
